In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

In [23]:
data = pd.read_csv('./train.csv')
y = data['Survived']
passenger_id = data['PassengerId']

data.drop(['Survived', 'Cabin', 'Ticket', 'Name', 'PassengerId'], axis=1, inplace=True)
X_train, X_valid, y_train, y_valid = train_test_split(data, y, test_size=0.2, random_state=39)
data

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [24]:
oneHotEncoder = OneHotEncoder(sparse_output=False)
data_oneHot = oneHotEncoder.fit_transform(data[["Embarked"]])
data_oneHot

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [25]:
cols = oneHotEncoder.get_feature_names_out(["Embarked"])
data_oneHot_df = pd.DataFrame(data_oneHot, columns=cols, index=data.index)
data = pd.concat([data.drop("Embarked", axis=1), data_oneHot_df], axis=1)
data.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
0,3,male,22.0,1,0,7.2500,0.0,0.0,1.0,0.0
1,1,female,38.0,1,0,71.2833,1.0,0.0,0.0,0.0
2,3,female,26.0,0,0,7.9250,0.0,0.0,1.0,0.0
3,1,female,35.0,1,0,53.1000,0.0,0.0,1.0,0.0
4,3,male,35.0,0,0,8.0500,0.0,0.0,1.0,0.0

In [26]:
cols

array(['Embarked_C', 'Embarked_Q', 'Embarked_S', 'Embarked_nan'],
      dtype=object)