In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt     
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit

data = pd.read_csv('../data/housing.csv')

# median_income => median_house_value

In [2]:
# Splitting the data

data['median_income_cat'] = pd.qcut(data["median_income"], q=5, labels=False)
data_splitter = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=3)

for train_index, test_index in data_splitter.split(data, data["median_income_cat"]):
    strat_train_set = data.loc[train_index]
    strat_test_set = data.loc[test_index]

In [3]:
# Detatching the target value
housing = strat_train_set.drop("median_house_value", axis=1)
housing_labes = strat_train_set["median_house_value"].copy()

In [ ]:
# OneHot Encoding

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
housing_cat = housing[['ocean_proximity']]
housing_cat_oneHot= encoder.fit_transform(housing_cat)

housing_cat_oneHot
housing_cat_oneHot_df = pd.DataFrame(housing_cat_oneHot, columns=encoder.get_feature_names_out())
housing_cat_oneHot_df

# Re-declaring the housing
housing_num = housing.drop("ocean_proximity", axis=1)
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_income_cat
6964,-118.06,33.99,47.0,1588.0,309.0,827.0,292.0,3.7833,2
19335,-122.85,38.52,13.0,4808.0,848.0,2568.0,762.0,3.6583,2
488,-122.26,37.86,52.0,2888.0,604.0,1253.0,538.0,3.3893,2
19072,-122.49,38.32,30.0,1631.0,284.0,788.0,284.0,3.3098,2
675,-122.17,37.69,24.0,2262.0,391.0,1125.0,366.0,4.7609,3
...,...,...,...,...,...,...,...,...,...
14043,-117.14,32.76,35.0,2539.0,661.0,1308.0,629.0,2.6777,1
9524,-123.17,39.18,14.0,2240.0,327.0,1030.0,308.0,5.9585,4
16951,-122.34,37.52,34.0,3559.0,560.0,1747.0,550.0,6.6959,4
16526,-121.20,37.80,37.0,311.0,61.0,171.0,54.0,4.0972,3
15453,-117.31,33.16,17.0,1704.0,263.0,781.0,281.0,5.6605,4

In [9]:
# OneHot Encoding

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
housing_cat_oneHot= encoder.fit_transform(housing_cat)

housing_cat_oneHot_df = pd.DataFrame(housing_cat_oneHot, columns=encoder.get_feature_names_out())
housing_cat_oneHot_df

,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...
16507,0.0,0.0,0.0,0.0,1.0
16508,1.0,0.0,0.0,0.0,0.0
16509,0.0,0.0,0.0,0.0,1.0
16510,0.0,1.0,0.0,0.0,0.0
16511,0.0,0.0,0.0,0.0,1.0

In [11]:
#  Delete the row only ONCE
housing.join(housing_cat_oneHot_df)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_income_cat,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
6964,-118.06,33.99,47.0,1588.0,309.0,827.0,292.0,3.7833,2,0.0,1.0,0.0,0.0,0.0
19335,-122.85,38.52,13.0,4808.0,848.0,2568.0,762.0,3.6583,2,NaN,NaN,NaN,NaN,NaN
488,-122.26,37.86,52.0,2888.0,604.0,1253.0,538.0,3.3893,2,0.0,0.0,0.0,0.0,1.0
19072,-122.49,38.32,30.0,1631.0,284.0,788.0,284.0,3.3098,2,NaN,NaN,NaN,NaN,NaN
675,-122.17,37.69,24.0,2262.0,391.0,1125.0,366.0,4.7609,3,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14043,-117.14,32.76,35.0,2539.0,661.0,1308.0,629.0,2.6777,1,0.0,0.0,0.0,0.0,1.0
9524,-123.17,39.18,14.0,2240.0,327.0,1030.0,308.0,5.9585,4,0.0,0.0,0.0,1.0,0.0
16951,-122.34,37.52,34.0,3559.0,560.0,1747.0,550.0,6.6959,4,NaN,NaN,NaN,NaN,NaN
16526,-121.20,37.80,37.0,311.0,61.0,171.0,54.0,4.0972,3,NaN,NaN,NaN,NaN,NaN
15453,-117.31,33.16,17.0,1704.0,263.0,781.0,281.0,5.6605,4,0.0,0.0,0.0,0.0,1.0

In [12]:
# Pipeline : imputer, scaler

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer


num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('std_scaler', StandardScaler())
])

housing_num_tr = num_pipeline.fit_transform(housing)

In [13]:
housing_num_tr

array([[ 7.48370544e-01, -7.64151588e-01,  1.46109453e+00, ...,
        -5.38776421e-01, -4.51939289e-02,  2.56911763e-04],
       [-1.64680379e+00,  1.36312895e+00, -1.24164342e+00, ...,
         6.81695767e-01, -1.11229855e-01,  2.56911763e-04],
       [-1.35178232e+00,  1.05319404e+00,  1.85855599e+00, ...,
         1.00023916e-01, -2.53339169e-01,  2.56911763e-04],
       ...,
       [-1.39178523e+00,  8.93530599e-01,  4.27694723e-01, ...,
         1.31184908e-01,  1.49349598e+00,  1.41429926e+00],
       [-8.21743738e-01,  1.02501814e+00,  6.66171600e-01, ...,
        -1.15680276e+00,  1.20635489e-01,  7.07278084e-01],
       [ 1.12339784e+00, -1.15391822e+00, -9.23674249e-01, ...,
        -5.67340664e-01,  9.46507197e-01,  1.41429926e+00]])

In [14]:
from sklearn.compose import ColumnTransformer

num_attribs = list(housing)
cat_attribs = ["ocean_proximity"]

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

housing_prepared = full_pipeline.fit_transform(housing)

ValueError: A given column is not a column of the dataframe