In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error
import pandas as pd


# without scaling MSE : 915

In [ ]:
train_full = pd.read_csv('./train.csv') 
y_full = pd.read_csv('./test.csv') 


train_full.drop(['Id'], axis=1, inplace=True)
train_full = train_full.select_dtypes(include=['float64', 'int64'])
X = train_full.drop(columns=['SalePrice'])
y = train_full['SalePrice']
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3, random_state=42)

X_train

In [32]:
y_full

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

model = RandomForestRegressor(random_state=42)

param_grid = {
    "n_estimators": [100, 300],
    "max_depth": [3, 5],
    "min_samples_split": [2, 4],
    "min_samples_leaf": [1, 2]
}

grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

In [ ]:
model = grid_search.best_estimator_

y_pred = grid_search.predict(X_valid)
mse = mean_squared_error(y_valid, y_pred)
print("Validation MSE:", mse/1000000)

In [34]:
test_data = pd.read_csv("./test.csv")
test_data = test_data[X_train.columns]  # keep only the numeric columns the model was trained on

submission_data = grid_search.predict(test_data)

submission_df = pd.DataFrame({
    'Id': y_full['Id'],
    'SalePrice': submission_data
})

submission_df.to_csv('submission_5.csv', index=False)
submission_df

        Id      SalePrice
0     1461  123253.298675
1     1462  146736.312615
2     1463  178912.689996
3     1464  181647.200855
4     1465  215910.484351
...    ...            ...
1454  2915   96063.035581
1455  2916  100739.591251
1456  2917  156402.430834
1457  2918  119454.531087
1458  2919  219483.350620

[1459 rows x 2 columns]